import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from '/data/bestArtists_RS.json'
import { useState } from 'react';
import Link from 'next/link';
import Router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [showData, setShowData] = useState(false);

  const handleClick = () => {
    const randomIndex = Math.floor(Math.random() * record.length);
    const randomRecord = record[randomIndex];
    Router.push({
      pathname: '/artist',
      query: { artist: randomRecord.Artist }
    });
  };

  console.log(record);

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
        <button onClick={handleClick}>Show data</button>
        {showData && (
  <div>
    <div>{showData.Artist}</div>
  </div>
)}
        </div>
      </main>
    </>
  )
}
